name: Release

on:
      workflow_dispatch:
            inputs:

jobs:
      build_and_release:
            permissions:
                  contents: write

            strategy:
                  fail-fast: false
                  matrix:
                        include:
                              - platform: macos-latest
                                args: '--target x86_64-apple-darwin'
                                name: MacOS (Intel)
                              - platform: 'windows-latest'
                                args: ''
                                name: Windows (x64)

            name: ${{ matrix.name }}
            runs-on: ${{ matrix.platform }}
            steps:
                  - name: Check out project
                    uses: actions/checkout@v4
                    with:
                          repository: openages/if_electron
                          token: ${{ secrets.IF_ELECTRON_ACCESS_TOKEN }}
                          ref: master

                  - name: setup node
                    uses: actions/setup-node@v4
                    with:
                          node-version: 23.5.0

                  - name: Setup python
                    uses: actions/setup-python@v4
                    with:
                          python-version: 3.9

                  - name: Setup pnpm
                    uses: pnpm/action-setup@v4
                    with:
                          version: 9

                  - name: Install deps
                    run: pnpm install

                  - name: MacOS:Import Apple Certificate (Developer ID)
                    env:
                          APPLE_CERTIFICATE: ${{ secrets.DEVELOPER_ID_CERTIFICATE }}
                          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.DEVELOPER_ID_PASSWORD }}
                    run: |
                          echo "$APPLE_CERTIFICATE" | base64 --decode -o certificate.p12
                          security import certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "$APPLE_CERTIFICATE_PASSWORD"
                          security set-key-partition-list -S apple-tool:,apple: -s -k "$APPLE_CERTIFICATE_PASSWORD" ~/Library/Keychains/login.keychain-db

                  - name: MacOS:Build on
                    if: matrix.platform == 'macos-latest'
                    run: pnpm run release:mac

                  - name: Windows:Build
                    if: matrix.platform == 'windows-latest'
                    run: |
                          pnpm run id:win
                          pnpm run clean_win_release

                  - name: windows:Remove blockmap
                    if: matrix.platform == 'windows-latest'
                    shell: pwsh
                    run: rm release/win32/x64/*.blockmap

                  - name: Upload on windows
                    if: matrix.platform == 'windows-latest'
                    uses: ryand56/r2-upload-action@latest
                    with:
                          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
                          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
                          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
                          r2-bucket: ${{ secrets.R2_BUCKET }}
                          source-dir: release/win32/x64
                          destination-dir: release/win32/x64
